version: "3"
services:
  back:
    image: back-i
    build: ./Back-end Project/app
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:8000/projet_pds
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=mahdi
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: projet_pds
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '8000:8000'
    volumes:
      - projet_pds:/var/lib/postgresql/data

  front:
    image: front-i
    build: ./projet_angular

volumes:
  projet_pds:
